version: '3'
services:
  soldier-starter:
    build: .
    image: soldier-starter:latest
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb:27017/soldierfactory?authSource=admin
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"

# avoid conflicts with secret network
networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/16
